2 style
Noiker-ux/HomeWork-React pull request #2
Opened 2024-01-21 10:51 UTC by Noiker-ux

2024-01-22 18:02 UTC, Levitinn commented
![image](https://github.com/Noiker-ux/HomeWork-React/assets/44999446/e1a70931-9c0c-4229-aa3f-b34de16763b2)
кажется, что то не так со стилями этого блока

2024-01-22 18:24 UTC, Levitinn requested changes

2024-01-22 18:24 UTC, Levitinn commented on src/components/Menu/Menu.jsx
> +				<li className={style['menu-item']}><a href="#" className={style['menu-link']}>Поиск фильмов</a></li>
каждый тег с новой строки. исключение - когда строка маленькая (например `<div><span>example</span></div>`

2024-01-22 18:24 UTC, Levitinn commented on src/components/Authtorization/Authtorization.jsx
> +		if (haveProfile===undefined && inpValue.trim().length){
if (!haveProfile && inpValue.trim().length) ......

2024-01-22 18:24 UTC, Levitinn commented on src/components/Authtorization/Authtorization.jsx
> +		const inpValue = refInputLog.current.value;
inputValue
не коверкай имена переменных=) 
в данном случае, сокращение не стоит того

2024-01-22 18:24 UTC, Levitinn commented on src/components/Authtorization/Authtorization.jsx
> +	const authtorization = (event) => {
эта функция - обработчик события click. все функции обработчики стоит называть со слова handle.
пример - handleAuth

2024-01-22 18:24 UTC, Levitinn commented on src/components/Authtorization/Authtorization.jsx
> +		const haveProfile = (dataFromLocalStorage.find(e=>e.name === inpValue));
( e=> e.name === inpValue) не теряй пробелы

2024-01-22 18:24 UTC, Levitinn commented on src/components/Authtorization/Authtorization.jsx
> +			const idProfile = (dataFromLocalStorage.findIndex(e=>e.name===inpValue));
const idProfile = лишние скобки -> (dataFromLocalStorage.findIndex(e=>e.name===inpValue));

2024-01-22 18:24 UTC, Levitinn commented on src/components/Authtorization/Authtorization.jsx
> +
лишние пустые строки

2024-01-22 18:24 UTC, Levitinn commented on src/components/Authtorization/Authtorization.jsx
логику авторизации уже нужно было делать? если да, то она не работает) в консоль вылетает ошибка
![image](https://github.com/Noiker-ux/HomeWork-React/assets/44999446/c48e91ff-227b-430e-b2d2-37aa3a58dfe1)

2024-01-22 18:24 UTC, Levitinn commented on src/components/Search/Search.jsx
> +				}/>
строка уехала

2024-01-22 18:24 UTC, Levitinn commented on src/components/FilmCard/FilmCard.jsx
> +					<a href="#">В избранное</a>
кнопка "в избранное" отдельный компонент со своей логикой внутри

2024-01-22 18:24 UTC, Levitinn commented on src/components/FilmsList/FilmsList.jsx
> +	if (data.length === 0){
if (!data.length) {.........}

2024-01-22 19:41 UTC, Noiker-ux commented on src/components/Menu/Menu.jsx
> +				<li className={style['menu-item']}><a href="#" className={style['menu-link']}>Поиск фильмов</a></li>
Исправил

2024-01-22 19:42 UTC, Noiker-ux commented on src/components/Authtorization/Authtorization.jsx
> +		if (haveProfile===undefined && inpValue.trim().length){
Исправил

2024-01-22 19:42 UTC, Noiker-ux commented on src/components/Authtorization/Authtorization.jsx
> +		const inpValue = refInputLog.current.value;
Исправил

2024-01-22 19:43 UTC, Noiker-ux commented on src/components/Authtorization/Authtorization.jsx
> +	const authtorization = (event) => {
Исправил

2024-01-22 19:44 UTC, Noiker-ux commented on src/components/Authtorization/Authtorization.jsx
> +		const haveProfile = (dataFromLocalStorage.find(e=>e.name === inpValue));
Исправил

2024-01-22 19:44 UTC, Noiker-ux commented on src/components/Authtorization/Authtorization.jsx
> +			const idProfile = (dataFromLocalStorage.findIndex(e=>e.name===inpValue));
Исправил

2024-01-22 19:45 UTC, Noiker-ux commented on src/components/Authtorization/Authtorization.jsx
> +
Исправил

2024-01-22 19:45 UTC, Noiker-ux commented on src/components/Search/Search.jsx
> +				}/>
Исправил

2024-01-22 19:46 UTC, Noiker-ux commented on src/components/FilmsList/FilmsList.jsx
> +	if (data.length === 0){
Исправил

2024-01-22 19:51 UTC, Noiker-ux commented on src/components/Authtorization/Authtorization.jsx
Там, просто прикол в том, что у тебя изначально должен быть в LocalStorage ключ profiles и тогда все гуд, но сейчас добавил надстройку, чтоб он генерировался и не надо было лезть в память

2024-01-23 18:09 UTC, Levitinn approved these changes

2024-01-23 18:09 UTC, Levitinn commented on src/components/Menu/Menu.jsx
> +	const exit = (e) => {
handleExit

2024-03-26 14:08 UTC, merged