4 data
Noiker-ux/HomeWork-React pull request #4
Opened 2024-02-03 18:55 UTC by Noiker-ux

2024-02-05 18:19 UTC, Levitinn requested changes

2024-02-05 18:19 UTC, Levitinn commented on src/main.tsx
> +          const { data } = await axios.get(`${PREFIX}/games?key=${API_KEY}`);
переименуй PREFIX, неочевидное название

2024-02-05 18:19 UTC, Levitinn commented on src/context/user.context.tsx
> +	const [profile, setProfile] = useState<IUser>({...profileForContext});
зачем нужен стейт если у тебя есть эта дата в контекте? просто используй контекст, это тоже самое состояние которым можно управлять

2024-02-05 18:19 UTC, Levitinn commented on src/components/Search/Search.tsx
> +    <div className={style["search-block"]}>
если обернуть инпут и кнопку в тег формы, то набрав текст в инпуте, можно не тянуться до кнопки, а нажать энтер, и сработает кнопка

2024-02-05 18:19 UTC, Levitinn commented on src/components/GamesList/GamesList.tsx
> +        <GameCard props={game} key={game.id} />
пропущен атрибут key внутри паб. его обязательно нужно указывать

2024-02-05 18:19 UTC, Levitinn commented on src/components/GameCard/GameCard.tsx
> +  // state array images for slider
нужно убрать лишние комментарии

2024-02-05 18:19 UTC, Levitinn commented on src/components/GameCard/GameCard.tsx
> +  let images: any = [];
под слайдер и баннер игры лучше сделай отдельный компонент. то что ты завел переменную, внутри которой добавляешь картинки, не делает эту переменную реактивной, а так же, вносит доп.логику в компонент GameCard, которая там необязательна. так код будет чище

2024-02-05 18:19 UTC, Levitinn commented on src/pages/MainPage/MainPage.tsx
> +import { IFilm } from "../../assets/IGame";
не используется

2024-02-05 18:19 UTC, Levitinn commented on src/pages/MainPage/MainPage.tsx
> +  const [activeData, setActiveData] = useState<any>(data);
почему any?

2024-02-05 18:19 UTC, Levitinn commented on src/pages/DetailPage/DetailPage.tsx
> +import { Link, useLoaderData } from "react-router-dom";
Link и IPropsRatingLine не используются

2024-02-05 18:19 UTC, Levitinn commented on src/pages/DetailPage/DetailPage.tsx
> +  const handleBlockGenre = () => {
не используется

2024-02-05 18:19 UTC, Levitinn commented on src/pages/DetailPage/DetailPage.tsx
> +  const handleJoiner = (key:any) => {
не очень нравится свичт внутри этой функции, может, как то без него обойтись?

2024-02-05 18:19 UTC, Levitinn commented on src/pages/DetailPage/DetailPage.tsx
> +  console.log(data);
убрать

2024-02-05 18:19 UTC, Levitinn commented on src/pages/DetailPage/DetailPage.tsx
> +            <div className={style["infoblocks"]}>
очень похожие друг на друга блоки, кажется, можно мапом пройтись по нужной дате и отрендерить эти однотипные блоки. И код станет намного меньше и чище

2024-02-06 07:11 UTC, Noiker-ux commented on src/main.tsx
> +          const { data } = await axios.get(`${PREFIX}/games?key=${API_KEY}`);
Исправил

2024-02-06 10:21 UTC, Noiker-ux commented on src/pages/DetailPage/DetailPage.tsx
> +  console.log(data);
Готово

2024-02-06 10:21 UTC, Noiker-ux commented on src/pages/DetailPage/DetailPage.tsx
> +  const handleBlockGenre = () => {
Убрал

2024-02-06 10:26 UTC, Noiker-ux commented on src/pages/DetailPage/DetailPage.tsx
> +import { Link, useLoaderData } from "react-router-dom";
Убрал

2024-02-06 10:29 UTC, Noiker-ux commented on src/components/Search/Search.tsx
> +    <div className={style["search-block"]}>
Исправил

2024-02-06 10:30 UTC, Noiker-ux commented on src/components/GameCard/GameCard.tsx
> +  // state array images for slider
Убрал

2024-02-06 10:34 UTC, Noiker-ux commented on src/pages/MainPage/MainPage.tsx
> +import { IFilm } from "../../assets/IGame";
Убрал

2024-02-06 10:35 UTC, Noiker-ux commented on src/pages/MainPage/MainPage.tsx
> +  const [activeData, setActiveData] = useState<any>(data);
Исправил

2024-02-06 13:04 UTC, Noiker-ux commented on src/context/user.context.tsx
> +	const [profile, setProfile] = useState<IUser>({...profileForContext});
Так ведь котекст, это хук который открывает видимость чего либо на любом уровне вложенности. Мне нужно было чтобы у меня был стейт и возможность его менять в точке authtorization

2024-02-06 13:04 UTC, Noiker-ux commented on src/components/GamesList/GamesList.tsx
> +        <GameCard props={game} key={game.id} />
тут есть кей

2024-02-06 14:46 UTC, Noiker-ux commented on src/pages/DetailPage/DetailPage.tsx
> +            <div className={style["infoblocks"]}>
Непонимаю где использовать мап, я вынес инфоблоки в отдельный компонентик, так меньше кода

2024-02-06 19:11 UTC, Levitinn commented on src/context/user.context.tsx
> +	const [profile, setProfile] = useState<IUser>({...profileForContext});
согласен. это я запутался в компонентах)

2024-02-06 19:17 UTC, Levitinn commented on src/pages/DetailPage/DetailPage.tsx
> +import { Link, useLoaderData } from "react-router-dom";
> Убрал

в этом компоненте есть еще неиспользуемые импорты

2024-02-06 19:17 UTC, Levitinn commented on src/pages/DetailPage/DetailPage.tsx
> +            <div className={style["infoblocks"]}>
> Непонимаю где использовать мап, я вынес инфоблоки в отдельный компонентик, так меньше кода

из пропа details ты можешь вынести в массив genres, platforms, released и тд. и рендерить их через map

2024-02-06 19:18 UTC, Levitinn requested changes
оставил комментарии

2024-02-07 19:57 UTC, Levitinn approved these changes

2024-03-26 14:08 UTC, merged