5 redux
Noiker-ux/HomeWork-React pull request #5
Opened 2024-02-12 15:40 UTC by Noiker-ux

2024-02-13 15:18 UTC, Levitinn requested changes
главная страница падает

2024-02-13 15:18 UTC, Levitinn commented on src/assets/IGame.ts
> +}
идентичные типы

2024-02-13 15:18 UTC, Levitinn commented on src/assets/IGame.ts
> +}
ниже такие же есть

2024-02-15 20:18 UTC, Levitinn requested changes
Проверил насколько хватило сил. невозможно читать код без пробелов и отступов. пройдись по всем компонентам и сделай нужные пробелы\отступы

2024-02-15 20:18 UTC, Levitinn commented on src/components/Menu/Menu.tsx
> +	const exit = (e:MouseEvent) => {
это логика авторизации, которая не имеет никакого отношения к компоненту Меню. нужно вынести отсюда эту лишнюю логику туда, где ей место.

2024-02-15 20:18 UTC, Levitinn commented on src/components/GameCard/GameCard.tsx
> +    const idxProfile = arrProfile.findIndex((e:any) => {return e.isLogined==true})
const idxProfile = arrProfile.findIndex((e:any) => e.isLogined)
и тебе нужно описать тип arrProfile, тогда ты сможешь убрать отсюда any.

2024-02-15 20:18 UTC, Levitinn commented on src/components/GameCard/GameCard.tsx
> +            {games.find((e:number)=> {return e == id})?<img src="./public/Bookmark.svg" alt="Bookmark"/>:<img src="./public/like.svg" alt="Like"/>}
- вот эта колбаса длинная тоже выглядит просто ужасно и невозможно читать. 
для начала вынеси это в отдельный компонент (кнопку в изранное) и внутри нее пусть будет логика состояния кнопки и все обработчики с ней связанные.
 - games.find( (game: number) => game  === id    вот такой вид должен быть у строки. с соблюдением всех пробелов и отступов, иначе это просто невозможно читать

2024-02-19 16:05 UTC, Noiker-ux commented on src/components/Menu/Menu.tsx
> +	const exit = (e:MouseEvent) => {
Вынес

2024-02-19 16:42 UTC, Noiker-ux commented on src/components/GameCard/GameCard.tsx
> +            {games.find((e:number)=> {return e == id})?<img src="./public/Bookmark.svg" alt="Bookmark"/>:<img src="./public/like.svg" alt="Like"/>}
Сделал

2024-02-19 16:57 UTC, Noiker-ux commented on src/components/GameCard/GameCard.tsx
> +    const idxProfile = arrProfile.findIndex((e:any) => {return e.isLogined==true})
поправил

2024-02-19 19:27 UTC, Levitinn commented on src/assets/IGame.ts
> +}
не исправлено

2024-02-19 19:33 UTC, Levitinn commented on src/components/Menu/Menu.tsx
> +	const { name, isLogined} = useSelector((s:RootState) => s.profile)
не вынес. под иконку авторизации лучше сделать отдельный компонент, и засунуть туда всю логику отображения

2024-02-19 19:33 UTC, Levitinn commented on src/components/GameCard/GameCard.tsx
> +    const idxProfile = arrProfile.findIndex((e:any) => {return e.isLogined==true})
посмотри внимательно на мой пример и на свой. в моем нет ретерна и фигурных скобок.
и вообще, код в этой функции можно сильно сократить. подумай над тем как сделать это. сейчас очень тяжело все это прочитать и уловить мысль

2024-02-19 19:34 UTC, Levitinn commented on src/components/GameCard/GameCard.tsx
> +            {games.find((e:number)=> {return e == id})?<img src="./public/Bookmark.svg" alt="Bookmark"/>:<img src="./public/like.svg" alt="Like"/>}
оба пункта не выполнены

2024-02-20 07:58 UTC, Noiker-ux commented on src/components/Menu/Menu.tsx
> +	const { name, isLogined} = useSelector((s:RootState) => s.profile)
Сделал

2024-02-21 09:33 UTC, Noiker-ux commented on src/components/GameCard/GameCard.tsx
> +            {games.find((e:number)=> {return e == id})?<img src="./public/Bookmark.svg" alt="Bookmark"/>:<img src="./public/like.svg" alt="Like"/>}
вынес кнопку избранное в отдельный компонент + перенес туда логику

2024-02-21 09:34 UTC, Noiker-ux commented on src/components/Menu/Menu.tsx
> +	const exit = (e:MouseEvent) => {
я полностью деструктуризировал меню

2024-02-21 11:43 UTC, Noiker-ux commented on src/assets/IGame.ts
> +}
убрал

2024-02-21 12:13 UTC, Noiker-ux commented on src/components/GameCard/GameCard.tsx
> +    const idxProfile = arrProfile.findIndex((e:any) => {return e.isLogined==true})
Cократил

2024-02-21 14:09 UTC, Levitinn requested changes

2024-02-21 14:09 UTC, Levitinn commented on src/components/Menu/MenuItems/Exit.tsx
> +export default function Exit () {
компонент называется выход, но рендерит в том числе "войти". придумай другое название

2024-02-21 14:09 UTC, Levitinn commented on src/components/GameCard/FavoriteButton/FavoriteButton.tsx
> +	const addOrRemoveFromFavorite = (e: MouseEvent) => {
handleClickFavorite. все обработчики стоит называть со слова handle

2024-02-26 07:05 UTC, Noiker-ux commented on src/components/GameCard/FavoriteButton/FavoriteButton.tsx
> +	const addOrRemoveFromFavorite = (e: MouseEvent) => {
Готово

2024-02-26 11:09 UTC, Noiker-ux commented on src/components/Menu/MenuItems/Exit.tsx
> +export default function Exit () {
Готово

2024-02-26 13:07 UTC, Levitinn approved these changes

2024-03-26 14:08 UTC, merged